version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepassword
  MYSQL_DATABASE: sampledb
  REACT_APP_SERVER_PORT: 5000

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/dbCreate.sql:/docker-entrypoint-initdb.d/dbCreate.sql

  server:
    build: ./server
    depends_on:
      - mysql
    expose:
      - 5000
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    links:
      - mysql
    command: yarn start

  client:
    build: ./client
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    links:
      - server
    command: yarn start
